config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :contracts
  resources :allotments
  resources :ventures
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'empreendimentos' => 'ventures#index'
  get 'loteamentos' => 'allotments#index'
  get 'contratos' => 'contracts#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/venture.rb
class Venture < ApplicationRecord
end

app/controllers/ventures_controller.rb
class VenturesController < ApplicationController
  before_action :set_venture, only: [:show, :edit, :update, :destroy]

  # GET /ventures
  # GET /ventures.json
  def index
    @ventures = Venture.all
  end

  # GET /ventures/1
  # GET /ventures/1.json
  def show
  end

  # GET /ventures/new
  def new
    @venture = Venture.new
  end

  # GET /ventures/1/edit
  def edit
  end

  # POST /ventures
  # POST /ventures.json
  def create
    @venture = Venture.new(venture_params)

    respond_to do |format|
      if @venture.save
        format.html { redirect_to @venture, notice: 'Venture was successfully created.' }
        format.json { render :show, status: :created, location: @venture }
      else
        format.html { render :new }
        format.json { render json: @venture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventures/1
  # PATCH/PUT /ventures/1.json
  def update
    respond_to do |format|
      if @venture.update(venture_params)
        format.html { redirect_to @venture, notice: 'Venture was successfully updated.' }
        format.json { render :show, status: :ok, location: @venture }
      else
        format.html { render :edit }
        format.json { render json: @venture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventures/1
  # DELETE /ventures/1.json
  def destroy
    @venture.destroy
    respond_to do |format|
      format.html { redirect_to ventures_url, notice: 'Venture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venture
      @venture = Venture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venture_params
      params.require(:venture).permit(:name, :readjust, :street, :neighborhood, :city)
    end
end

app/helpers/ventures_helper.rb
module VenturesHelper
end

app/views/ventures/_form.html.erb
<%= form_with(model: venture, local: true) do |form| %>
  <% if venture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venture.errors.count, "error") %> prohibited this venture from being saved:</h2>

      <ul>
      <% venture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label 'name', class: 'input-group-text' %>
    <%= form.text_field :name, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label 'readjust', class: 'input-group-text' %>
    <%= form.text_field :readjust, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label 'street', class: 'input-group-text' %>
    <%= form.text_field :street, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label 'neighborhood', class: 'input-group-text' %>
    <%= form.text_field :neighborhood, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label 'city', class: 'input-group-text' %>
    <%= form.text_field :city, class: 'form-control input_pass' %>
  </div>

  <div class="d-flex justify-content-center mt-3 login_container">
    <%= form.submit("Criar", :id=>"button", :class=>"btn login_btn", :name=>"submit") %>
  </div>
<% end %>

app/views/ventures/edit.html.erb
<div class="container h-200">
  <div class="d-flex justify-content-center h-200">
    <div class="d-flex justify-content-center form_container">
        <div class="user_card">
            <h1>Empreendimento</h1>

            <%= render 'form', venture: @venture %>
            <%= link_to 'Back', ventures_path, :class=>"btn back_btn" %>
        </div>
    </div>
  </div>
</div>

app/views/ventures/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Empreendimentos</h1>

  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Readjust</th>
        <th scope="col">Street</th>
        <th scope="col">Neighborhood</th>
        <th scope="col">City</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @ventures.each do |venture| %>
        <tr>
          <td><%= venture.name %></td>
          <td><%= venture.readjust %></td>
          <td><%= venture.street %></td>
          <td><%= venture.neighborhood %></td>
          <td><%= venture.city %></td>
          <td><%= link_to 'Edit', edit_venture_path(venture) %></td>
          <td><%= link_to 'Destroy', venture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <br>
  
  
  <%= link_to 'Novo', new_venture_path, :class=>"btn create_btn float-right" %>
</div>

app/views/ventures/new.html.erb
<div class="container h-200">
  <div class="d-flex justify-content-center h-200">
    <div class="d-flex justify-content-center form_container">
        <div class="user_card">
            <h1>Empreendimento</h1>

            <%= render 'form', venture: @venture %>
            <%= link_to 'Back', ventures_path, :class=>"btn back_btn" %>
        </div>
    </div>
  </div>
</div>

app/views/ventures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venture.name %>
</p>

<p>
  <strong>Readjust:</strong>
  <%= @venture.readjust %>
</p>

<p>
  <strong>Street:</strong>
  <%= @venture.street %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @venture.neighborhood %>
</p>

<p>
  <strong>City:</strong>
  <%= @venture.city %>
</p>

<%= link_to 'Edit', edit_venture_path(@venture) %> |
<%= link_to 'Back', ventures_path %>