config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :contracts
  resources :allotments
  resources :ventures
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'empreendimentos' => 'ventures#index'
  get 'loteamentos' => 'allotments#index'
  get 'contratos' => 'contracts#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-group mb-3">
      <%= form.label 'email', class: 'input-group-text' %>
      <%= form.text_field :email, class: 'form-control input_pass' %>
    </div>

    <div class="input-group mb-3">
      <%= form.label 'password', class: 'input-group-text' %>
      <%= form.password_field :password, class: 'form-control input_pass' %>
    </div>

    <div class="input-group mb-3">
      <%= form.label 'password_confirmation', class: 'input-group-text' %>
      <%= form.password_field :password_confirmation, class: 'form-control input_pass' %>
    </div>

    <div class="d-flex justify-content-center mt-3 login_container">
      <%= form.submit("Criar", :id=>"button", :class=>"btn login_btn", :name=>"submit") %>
    </div>
  <% end %>

app/views/users/_login.html.erb
<div class="user_card">
    <p id="alert"><%= alert %></p>
    <div class="d-flex justify-content-center">
        <div class="brand_logo_container">
            <%= image_tag("https://cdn.freebiesupply.com/logos/large/2x/pinterest-circle-logo-png-transparent.png", class:"brand_logo", alt: "Logo") %>
        </div>
    </div>
    <%= form_tag sessions_path do |form| %>
    <div class="input-group mb-3">
        <%= label_tag 'email', 'Email', class: 'input-group-text' %>
        <%= text_field_tag :email, 'Email', class: 'form-control input_pass' %>
    </div> 
    <div class="input-group mb-3">
        <%= label_tag 'password', 'Senha', class: 'input-group-text' %>
        <%= password_field_tag :password, 'Senha', class:'form-control input_pass' %>
    </div>
    <div class="d-flex justify-content-center mt-3 login_container">
        <%= submit_tag("Login", :id=>"button", :class=>"btn login_btn", :name=>"submit") %>
    </div>
    <div class="mt-4">
        <div class="d-flex justify-content-center links">
           Já possui conta ? <a href="<%= signup_path %>" class="ml-2">Sign Up</a>
        </div>
    </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container h-100">
  <div class="d-flex justify-content-center h-100">
    <div class="d-flex justify-content-center form_container">
        <div class="user_card">
            <%= render 'form', user: @user %>

            <%= link_to 'Back', root_path, :class=>"btn back_btn" %>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>