config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :contracts
  resources :allotments
  resources :ventures
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'empreendimentos' => 'ventures#index'
  get 'loteamentos' => 'allotments#index'
  get 'contratos' => 'contracts#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allotment.rb
class Allotment < ApplicationRecord
  belongs_to :venture
end

app/controllers/allotments_controller.rb
class AllotmentsController < ApplicationController
  before_action :set_allotment, only: [:show, :edit, :update, :destroy]

  # GET /allotments
  # GET /allotments.json
  def index
    @allotments = Allotment.all
  end

  # GET /allotments/1
  # GET /allotments/1.json
  def show
  end

  # GET /allotments/new
  def new
    @allotment = Allotment.new
    @empreendimentos = Venture.all
  end

  # GET /allotments/1/edit
  def edit
    @empreendimentos = Venture.all
  end

  # POST /allotments
  # POST /allotments.json
  def create
    @allotment = Allotment.new(allotment_params)

    respond_to do |format|
      if @allotment.save
        format.html { redirect_to @allotment, notice: 'Allotment was successfully created.' }
        format.json { render :show, status: :created, location: @allotment }
      else
        format.html { render :new }
        format.json { render json: @allotment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allotments/1
  # PATCH/PUT /allotments/1.json
  def update
    respond_to do |format|
      if @allotment.update(allotment_params)
        format.html { redirect_to @allotment, notice: 'Allotment was successfully updated.' }
        format.json { render :show, status: :ok, location: @allotment }
      else
        format.html { render :edit }
        format.json { render json: @allotment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allotments/1
  # DELETE /allotments/1.json
  def destroy
    @allotment.destroy
    respond_to do |format|
      format.html { redirect_to allotments_url, notice: 'Allotment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allotment
      @allotment = Allotment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allotment_params
      params.require(:allotment).permit(:name, :number, :value, :venture_id)
    end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/views/allotments/_form.html.erb
<%= form_with(model: allotment, local: true) do |form| %>
  <% if allotment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(allotment.errors.count, "error") %> prohibited this allotment from being saved:</h2>

      <ul>
      <% allotment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label 'name', class: 'input-group-text' %>
    <%= form.text_field :name, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label 'number', class: 'input-group-text' %>
    <%= form.text_field :number, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label 'value', class: 'input-group-text' %>
    <%= form.text_field :value, class: 'form-control input_pass' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :venture_id, class: 'input-group-text' %>
    <%= collection_select(:allotment, :venture_id, @empreendimentos, :id, :name) %>
  </div>

  <div class="d-flex justify-content-center mt-3 login_container">
    <%= form.submit("Criar", :id=>"button", :class=>"btn login_btn", :name=>"submit") %>
  </div>
<% end %>

app/views/allotments/edit.html.erb
<div class="container h-200">
  <div class="d-flex justify-content-center h-200">
    <div class="d-flex justify-content-center form_container">
        <div class="user_card">
            <h1>Loteamento</h1>

            <%= render 'form', allotment: @allotment %>
            <%= link_to 'Back', allotments_path, :class=>"btn back_btn" %>
        </div>
    </div>
  </div>
</div>

app/views/allotments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Allotments</h1>

  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Number</th>
        <th scope="col">Value</th>
        <th scope="col">Venture</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @allotments.each do |allotment| %>
        <tr>
          <td><%= allotment.name %></td>
          <td><%= allotment.number %></td>
          <td><%= allotment.value %></td>
          <td><%= allotment.venture.name %></td>
          <td><%= link_to 'Edit', edit_allotment_path(allotment) %></td>
          <td><%= link_to 'Destroy', allotment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_allotment_path, :class=>"btn create_btn float-right" %>
</div>

app/views/allotments/new.html.erb
<div class="container h-200">
  <div class="d-flex justify-content-center h-200">
    <div class="d-flex justify-content-center form_container">
        <div class="user_card">
            <h1>Loteamento</h1>

            <%= render 'form', allotment: @allotment %>
            <%= link_to 'Back', allotments_path, :class=>"btn back_btn" %>
        </div>
    </div>
  </div>
</div>

app/views/allotments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @allotment.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @allotment.number %>
</p>

<p>
  <strong>Value:</strong>
  <%= @allotment.value %>
</p>

<p>
  <strong>Venture:</strong>
  <%= @allotment.venture %>
</p>

<%= link_to 'Edit', edit_allotment_path(@allotment) %> |
<%= link_to 'Back', allotments_path %>