config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :contracts
  resources :allotments
  resources :ventures
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'empreendimentos' => 'ventures#index'
  get 'loteamentos' => 'allotments#index'
  get 'contratos' => 'contracts#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= home_index_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= empreendimentos_path %>">Empreendimentos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= loteamentos_path %>">Loteamentos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= contratos_path %>">Contratos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= logout_path %>">Log Out</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= render partial: "/layouts/menu" %>
    <% end %>
    <%= yield %>
  </body>
</html>